image:
  repository: jrebaza01/nats-subscriber
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

nats:
  url: nats://nats.nats.svc.cluster.local:4222
  subject: poc.events

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
