apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subscriber.fullname" . }}
  labels:
    app: {{ include "subscriber.name" . }}
data:
  NATS_URL: {{ .Values.nats.url | quote }}
  NATS_SUBJECT: {{ .Values.nats.subject | quote }}
