apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subscriber.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ include "subscriber.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "subscriber.name" . }}
    spec:
      containers:
        - name: subscriber
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
              - configMapRef:
                  name: {{ include "subscriber.fullname" . }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}

{{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pidof nats-subscriber
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
{{- end }}

